//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kp_hotel.v2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int idBooking { get; set; }
        public Nullable<int> idClient { get; set; }
        public Nullable<int> idStaff { get; set; }
        public Nullable<int> idRoom { get; set; }
        public Nullable<System.DateTime> CheckIn { get; set; }
        public Nullable<System.DateTime> CheckOut { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Room Room { get; set; }
    }
}
